fix: error when modules reference ../path
If module node reference a ../path, it triggers a configuration error
when Maven > Update is used as project - ../path lookup fails (as
illegal).

Stack example:

java.lang.IllegalArgumentException: Path must include project and resource name: /my-module
  at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
  at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2156)
  at org.eclipse.core.internal.resources.Container.getFolder(Container.java:200)